### ISSUE TITLE
Research about text component

### ISSUE THREAD

**Issue by michal367** [ostatni5/tk-2022#36]
DoD:
- [x] find component that finds if image contains any text
- [x] find component that finds if image contains specific text
- [x] test if this component works

Bonus:
- [x] both things are done by one component

**Comment by retkiewi** [comment]
Generally, any tesseract-based library should work. Preferably those that don't require the CPP library. Python is a good pick, java should also work.

**Comment by ostatni5** [comment]
Good research was helpful :D
