### ISSUE TITLE
Research about people component

### ISSUE THREAD

**Issue by michal367** [ostatni5/tk-2022#38]
DoD:
- [x] find component that finds any people on image
- [x] find component that finds specific amount of people
- [x] test if it works

Bonus:
- [x] both things are done by one component

**Comment by ostatni5** [comment]
ImageAI - Python:
https://github.com/OlafenwaMoses/ImageAI
https://towardsdatascience.com/object-detection-with-10-lines-of-code-d6cb4d86f606

OpenCV - Python:
https://data-flair.training/blogs/python-project-real-time-human-detection-counting/

Other  - Python:
https://medium.com/analytics-vidhya/best-open-source-and-free-custom-object-detection-python-repositories-libraries-3595446857e

OpenCV - C++:
https://www.youtube.com/watch?v=BCJYorKIlN8
https://stackoverflow.com/questions/31660271/improving-people-detection-with-opencv

**Comment by Derstilon** [comment]
- [x] **Approved**
