### ISSUE TITLE
Add more params to metadata component

### ISSUE THREAD

**Issue by michal367** [ostatni5/tk-2022#41]
DoD:
- [ ] decide what metadata params will be added
- [ ] add more metadata params

**Comment by retkiewi** [comment]
New parameters include: 
- [ ] Camera manufacturer,
- [ ] Camera model,
- [ ] Color space,
- [ ] Exposure time,
- [ ] f number,
- [ ] pixel x dimension,
- [ ] pixel y dimension.

**Comment by retkiewi** [comment]
Removed "color space", because the possible values are unclear.

**Comment by retkiewi** [comment]
Manufacturer is redundant with model
