### ISSUE TITLE
Research weather component

### ISSUE THREAD

**Issue by michal367** [ostatni5/tk-2022#43]
DoD:
- [x] find a component that classifies weather on image
- [x] find a component that finds if the image contains a specific weather type
- [x] test if this component works

Bonus:
- [x] both things are done by one component

**Comment by Derstilon** [comment]
https://github.com/shanerbo/PredictWeatherInImage
https://github.com/berkgulay/weather-prediction-from-image

**Comment by Derstilon** [comment]
@michal367 
![image](https://user-images.githubusercontent.com/26445545/162789074-2673113d-b435-4c59-ac38-a1a46084392a.png)
Result of tests for [PredictWeatherInImage](https://github.com/shanerbo/PredictWeatherInImage)

**Comment by Derstilon** [comment]
[weather-prediction-from-image](https://github.com/berkgulay/weather-prediction-from-image) has major issues with the current implementation of Keras module and no dependency was specified for working release.

**Comment by michal367** [comment]
Approved
